<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BinaryKits.Zpl.Viewer" Version="[1.3.1]" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="[3.119.1]" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="[8.3.1.2]" />
  </ItemGroup>
</Project>
