load("@npm_zpl_renderer_js//:defs.bzl", "npm_link_all_packages")
package(default_visibility = ["//visibility:public"])
exports_files(glob(["*.json", "*.mjs", "*.yaml"], allow_empty = True))
filegroup(name = "source_files", srcs = glob(["*.json", "*.mjs", "*.yaml"], allow_empty = True))
npm_link_all_packages()
